# Generated by Django 5.0.1 on 2024-11-20 03:00

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image_url",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="book_covers"
            ),
        ),
    ]
