# Generated by Django 5.0.1 on 2024-11-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_book_cover_image_book_google_books_id_book_is_manual_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="is_manual",
        ),
        migrations.AddField(
            model_name="book",
            name="openlibrary_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="book",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Upload"),
                    ("google", "Google Books API"),
                    ("openlibrary", "Open Library"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
