# Generated by Django 5.1.3 on 2024-11-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userbook_users_userb_user_id_14fcc3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='google_books_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
