# Generated by Django 5.1.3 on 2024-11-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_book_google_books_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
